# Generated by Django 5.2.7 on 2026-09-22 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('jogos', models.PositiveIntegerField(default=0)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('gols_pro', models.PositiveIntegerField(default=0)),
                ('gols_contra', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(blank=True, null=True, unique=True)),
                ('rodada', models.IntegerField()),
                ('gols_mandante', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
                ('amarelos', models.IntegerField(default=0)),
                ('vermelhos', models.IntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to='core.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='core.time')),
            ],
        ),
    ]
