# Generated by Django 5.2.7 on 2026-09-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='escudo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='id_api',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='time',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='derrotas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='empates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='gols_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='gols_pro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='jogos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='time',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='vitorias',
            field=models.IntegerField(default=0),
        ),
    ]
