# Generated by Django 5.2.7 on 2026-09-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_time_escudo_time_id_api_time_sigla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='cartoes_amarelos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='cartoes_vermelhos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='escudo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='id_api',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='time',
            name='sigla',
            field=models.CharField(max_length=3),
        ),
    ]
