# Generated by Django 5.2.7 on 2026-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_time_cartoes_amarelos_time_cartoes_vermelhos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='posicao_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
